services:
  frontend:
    image: shavbb/portfolio-frontend
    ports:
      - "3000:80"  # Host port 3000 to Nginx port 80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: shavbb/portfolio-backend
    ports:
      - "5010:5010"
    networks:
      - app-network

networks:
  app-network:
