services:
  frontend:
    image: shavbb/portfolio-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: shavbb/portfolio-backend
    ports:
      - "5010:5010"
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
