# .github/workflows/deploy.yml
name: Deploy to AWS EC2 (Self-hosted)

on:
  workflow_run:
    workflows: ["portfolio CI"] # CI workflow name
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Pull latest Docker images
        run: |
          docker compose pull

      - name: Start containers
        run: |
          docker compose up -d --remove-orphans
